//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiShop.Models.EzShopV20
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInfor
    {
        public long CustomerID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Photo { get; set; }
        public Nullable<bool> Activated { get; set; }
        public string Address { get; set; }
    }
}
