//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiShop.Models.EzShopV20
{
    using System;
    using System.Collections.Generic;
    
    public partial class Priority
    {
        public int id { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<double> bestSellingNC { get; set; }
        public Nullable<double> bestSellingTranditional { get; set; }
        public Nullable<double> purchasedItem { get; set; }
        public Nullable<double> notpurchased { get; set; }
        public Nullable<double> newItemTranditional { get; set; }
    }
}
